### ISSUE TITLE
Varios

### ISSUE THREAD

**Issue by slipcs** [ECYS-USAC/cpfecys#66]
Que tal, me gustaria dar a conocer algunos inconvenientes que he visto hasta el momento.

- La fecha y hora que muestra el sistema parece ser el quivocado.
- Las imagenes que hay que subir al parecer deben ser exactamente de 200x300 (no se si se pueda permitir una variante que sea similar al tamaño especificado o si debe ser exactamente el tamaño solicitado)
- Tambien se muestran 2 mensajes como no leidos y al ingresar al area de mensajes ya estan leidos todos los mensajes.

**Comment by lecatavo** [comment]
•	La hora del servidor era incorrecta. Ya fue corregida.
•	Las imágenes pueden ser menores al tamaño especificado.
•	Podrías enviar un correo con tus datos a soporte@dtt-ecys.org para estudiar el problema de los correos.

Gracias por las observaciones

**Comment by lecatavo** [comment]
• Los correos que se muestran son del semestre anterior
