### ISSUE TITLE
Información Sensible

### ISSUE THREAD

**Issue by dlobregon** [ECYS-USAC/cpfecys#67]
Algunos archivos tienen información sensible, me imagino que ya saben cuales son!

**Comment by jossemarGT** [comment]
+1 :+1:

**Comment by omarvides** [comment]
Buenísimo, por que no hace alguien de ustedes un pull request con el fix? :)

**Comment by troyanrex** [comment]
:+1: Si alguien ya lo descargo o ya hizo un fork no se arregla, aunque se recurriera a purgar los datos de esta forma
https://help.github.com/articles/remove-sensitive-data/
Saludos :D
